### ISSUE TITLE
Desafio

### ISSUE THREAD

**Issue by vlamirsanto** [hurbcom/challenge-alpha#12]
Bom dia!
O desafio ainda está de pé? Vi que a url da api não está funcionando, e sim, redirecionando para uma página do site.

**Comment by BelfDev** [comment]
> Bom dia!
> O desafio ainda está de pé? Vi que a url da api não está funcionando, e sim, redirecionando para uma página do site.

Fala @vlamirsanto ! Acabei de atualizar o desafio, está super de pé. Dá uma olhada lá no README de novo e mandar bala.

Quaisquer dúvidas é só perguntar. Boa sorte!

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.
