### ISSUE TITLE
Dúvida na API Request

### ISSUE THREAD

**Issue by carloshmartins** [hurbcom/challenge-alpha#14]
No texto foi falado que o primeiro GET pegaria uma lista de hotéis de Búzios, porém a Query é de Gramado. Fiquei um pouco confuso.

Posso considerar então que a Query será Gramado e no app desafio eu faria uma busca localmente em cima desse Request já feito(Gramado no caso)?

**Comment by thiagocortat** [comment]
Olá @carloshmartins 
Consertamos a chamada para trazer os resultados de Búzios.

**Comment by carloshmartins** [comment]
@thiagocortat Eu notei que o response JSON vem com mais detalhes e alguns atributos que me permitam implementar novas features. Vou dar uma olhada e te falo se tiver algum problema. Obrigado
