### ISSUE TITLE
Ordenar pela ordem de estrelas

### ISSUE THREAD

**Issue by cristianopcortez** [hurbcom/challenge-alpha#31]
De acordo com o README deve-se estar ordenado descrentemente pela quantidade de estrelas. Qual chamada na API faço para executar o resultado da busca com essa ordenação ?

**Comment by bernardog** [comment]
Estou implementando uma lista infinita de hotéis, mas para ordená-los por quantidade de estrelas, precisaria determinar a ordenação já na chamada... É possível?
