### ISSUE TITLE
Dúvda referente ao consumo dos dados

### ISSUE THREAD

**Issue by ffeliciodeveloper** [hurbcom/challenge-alpha#51]
Bom dia.

Estou participando do processo e gostaria de tirar algumas dúvidas referente ao consumo dos dados:

1. Sobre as informações contidas na pasta **examples**, é para fazer o consumo direto dos dados mockados nos arquivos **hotel.json** e **packages.json**?
2. Ainda sobre o consumo dos dados, as informações contidas na pasta **examples** são só para exemplos e utilizar algum recurso específico fornecido pela Hurb para poder utilizar?
3. Será necessário eu utilizar algum serviço de cloud para expor as informações contidas nos arquivos **hotel.json** e **packages.json** e fazer o consumo no app?

Desde já, agradeço muito pela oportunidade de participar do processo.
Espero poder fazer parte do time.
Obrigado.

**Comment by danielpucci** [comment]
Olá @ffeliciodeveloper , ficamos felizes com o seu interesse por nós!! 😃 
Estamos hoje apenas com implementação utilizando graphql.
Segue os links da nossa wiki:
[Sugestões](https://github.com/hurbcom/challenge-alpha/wiki/GraphQL-Suggestion)
[Busca de pacotes](https://github.com/hurbcom/challenge-alpha/wiki/GraphQL-Search-Package)
[Busca de hoteis](https://github.com/hurbcom/challenge-alpha/wiki/GraphQL-Search-Hotel)
[Busca completa](https://github.com/hurbcom/challenge-alpha/wiki/GraphQL-Search)

Qualquer dúvida, só nos avisar! 😃

**Comment by ffeliciodeveloper** [comment]
Tudo bem @danielpucci ?

Desculpe por te incomodar e agradeço muito a sua ajuda em se dispor a responder.

Muito obrigado mesmo.

Espero fazer um bom projeto e conseguir fazer parte da família Hurb.

Obrigado!
